name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # take all the code out of this project
      - uses: actions/checkout@v2
      # change into a directory, install dependencies and run the 'test' script
      - run: cd auth && npm install && npm run test:ci
