name: tests-tickets
# on pull request when any files in the specified directory has been changed
on:
  pull_request:
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # take all the code out of this project
      - uses: actions/checkout@v4
      # change into a directory, install dependencies and run the 'test:ci' script
      - run: cd tickets && npm install && npm run test:ci
